pip3 install flask
pip3 install scikit-image
pip3 install scikit-learn
pip3 install pillow
pip3 install resize-image
pip3 install numpy
pip3 install matplotlib
pip3 install keras
pip3 install tensorflow